/**
 * Canonical multilingual labels for dental ICD-10 codes (WHO / project seed).
 * Merged over DB rows so missing or English-only category/description still resolve per language.
 * @see seed_icd10_dental_codes.sql
 */

const BY_CODE = {
  "K00.0": {
    title_tr: "Anodonti",
    title_en: "Anodontia",
    title_ka: "ანოდონტია",
    title_ru: "Анодонтия",
    description_tr: "Doğuştan diş eksikliği",
    description_en: "Congenital absence of teeth",
    description_ka: "კონგენიტალური კბილების არარსებობა",
    description_ru: "Врожденное отсутствие зубов",
  },
  "K00.1": {
    title_tr: "Süpernümerer dişler",
    title_en: "Supernumerary teeth",
    title_ka: "ზედმეტი კბილები",
    title_ru: "Сверхкомплектные зубы",
    description_tr: "Normal diş sayısından fazla diş",
    description_en: "Teeth in excess of the normal complement",
    description_ka: "ნორმაზე მეტი კბილების რაოდენობა",
    description_ru: "Зубы в избытке нормального количества",
  },
  "K00.2": {
    title_tr: "Makrodonti",
    title_en: "Macrodontia",
    title_ka: "მაკროდონტია",
    title_ru: "Макродонтия",
    description_tr: "Anormal büyük dişler",
    description_en: "Abnormally large teeth",
    description_ka: "ანომალურად დიდი კბილები",
    description_ru: "Аномально большие зубы",
  },
  "K00.3": {
    title_tr: "Mikrodonti",
    title_en: "Microdontia",
    title_ka: "მიკროდონტია",
    title_ru: "Микродонтия",
    description_tr: "Anormal küçük dişler",
    description_en: "Abnormally small teeth",
    description_ka: "ანომალურად პატარა კბილები",
    description_ru: "Аномально маленькие зубы",
  },
  "K00.4": {
    title_tr: "Dislazi",
    title_en: "Dysplasia of enamel",
    title_ka: "ემალის დისპლაზია",
    title_ru: "Дисплазия эмали",
    description_tr: "Mineralizasyon bozukluğu",
    description_en: "Disturbance of enamel formation",
    description_ka: "ემალის ფორმირების დარღვევა",
    description_ru: "Нарушение формирования эмали",
  },
  "K01.0": {
    title_tr: "Çıkmamış diş",
    title_en: "Impacted teeth",
    title_ka: "ჩარჩობილი კბილები",
    title_ru: "Ретенированные зубы",
    description_tr: "Dişin çıkamaması",
    description_en: "Failure of tooth eruption",
    description_ka: "კბილის არ ამოსვლა",
    description_ru: "Невозможность прорезывания зуба",
  },
  "K01.1": {
    title_tr: "Gömülü diş",
    title_en: "Embedded teeth",
    title_ka: "ჩარჩობილი კბილები",
    title_ru: "Вколоченные зубы",
    description_tr: "Dişin kemik içinde kalması",
    description_en: "Tooth completely embedded in bone",
    description_ka: "კბილის ძვლის შიგნით სრულად მოთავსება",
    description_ru: "Зуб полностью погружен в кость",
  },
  "K02.0": {
    title_tr: "Mine çürüğü",
    title_en: "Caries limited to enamel",
    title_ka: "ემალის კარიესი",
    title_ru: "Кариес, ограниченный эмалью",
    description_tr: "Sadece mineyi etkileyen çürük",
    description_en: "Caries confined to enamel",
    description_ka: "კარიესი, რომელიც შემოფარულია ემალით",
    description_ru: "Кариес, ограниченный эмалью",
  },
  "K02.1": {
    title_tr: "Dentin çürüğü",
    title_en: "Caries of dentine",
    title_ka: "დენტინის კარიესი",
    title_ru: "Кариес дентина",
    description_tr: "Mine ve dentini etkileyen çürük",
    description_en: "Caries involving dentine",
    description_ka: "კარიესი, რომელიც მოიცავს დენტინს",
    description_ru: "Кариес, вовлекающий дентин",
  },
  "K02.2": {
    title_tr: "Pulpa çürüğü",
    title_en: "Caries of pulp",
    title_ka: "პულპის კარიესი",
    title_ru: "Кариес пульпы",
    description_tr: "Pulpayı etkileyen çürük",
    description_en: "Caries of pulp",
    description_ka: "პულპის კარიესი",
    description_ru: "Кариес пульпы",
  },
  "K02.3": {
    title_tr: "İleri çürük",
    title_en: "Arrested dental caries",
    title_ka: "შეჩერებული დენტალური კარიესი",
    title_ru: "Приостановленный кариес",
    description_tr: "Durmuş çürük lezyonu",
    description_en: "Inactive dental caries",
    description_ka: "არააქტიური დენტალური კარიესი",
    description_ru: "Неактивный кариес",
  },
  "K03.0": {
    title_tr: "Aşınma",
    title_en: "Attrition of teeth",
    title_ka: "კბილების ატრიბუცია",
    title_ru: "Атрития зубов",
    description_tr: "Diş yüzeyinin aşınması",
    description_en: "Wear of teeth",
    description_ka: "კბილების დაცემა",
    description_ru: "Износ зубов",
  },
  "K03.1": {
    title_tr: "Abrasyon",
    title_en: "Abrasion of teeth",
    title_ka: "კბილების აბრაზია",
    title_ru: "Абразия зубов",
    description_tr: "Mekanik aşınma",
    description_en: "Loss of tooth substance from mechanical factors",
    description_ka: "მექანიკური ფაქტორებისგან კბილის ნივთიერების დაკარგვა",
    description_ru: "Потеря вещества зуба от механических факторов",
  },
  "K03.2": {
    title_tr: "Erozyon",
    title_en: "Erosion of teeth",
    title_ka: "კბილების ეროზია",
    title_ru: "Эрозия зубов",
    description_tr: "Kimyasal aşınma",
    description_en: "Loss of tooth substance from non-bacterial chemical agents",
    description_ka: "არაბაქტერიული ქიმიური აგენტებისგან კბილის ნივთიერების დაკარგვა",
    description_ru: "Потеря вещества зуба от небактериальных химических агентов",
  },
  "K04.0": {
    title_tr: "Pulpit",
    title_en: "Pulpitis",
    title_ka: "პულპიტი",
    title_ru: "Пульпит",
    description_tr: "Pulpa iltihabı",
    description_en: "Inflammation of the pulp",
    description_ka: "პულპის ანთება",
    description_ru: "Воспаление пульпы",
  },
  "K04.1": {
    title_tr: "Nekroz",
    title_en: "Necrosis of pulp",
    title_ka: "პულპის ნეკროზი",
    title_ru: "Некроз пульпы",
    description_tr: "Pulpa ölümü",
    description_en: "Death of pulp",
    description_ka: "პულპის სიკვდილი",
    description_ru: "Смерть пульпы",
  },
  "K04.2": {
    title_tr: "Apikal periodontit",
    title_en: "Periapical abscess without sinus",
    title_ka: "პერიაპიკალური აბსცესი ურთიერთობის გარეშე",
    title_ru: "Периапикальный абсцесс без свища",
    description_tr: "Apikal abs",
    description_en: "Periapical abscess with sinus",
    description_ka: "პერიაპიკალური აბსცესი ურთიერთობით",
    description_ru: "Периапикальный абсцесс со свищом",
  },
  "K05.0": {
    title_tr: "Akut gingivit",
    title_en: "Acute gingivitis",
    title_ka: "მწვავე გინგივიტი",
    title_ru: "Острый гингивит",
    description_tr: "Akut diş eti iltihabı",
    description_en: "Acute inflammation of the gums",
    description_ka: "ღრძილების მწვავე ანთება",
    description_ru: "Острое воспаление десен",
  },
  "K05.1": {
    title_tr: "Kronik gingivit",
    title_en: "Chronic gingivitis",
    title_ka: "ქრონიკული გინგივიტი",
    title_ru: "Хронический гингивит",
    description_tr: "Kronik diş eti iltihabı",
    description_en: "Chronic inflammation of the gums",
    description_ka: "ღრძილების ქრონიკული ანთება",
    description_ru: "Хроническое воспаление десен",
  },
  "K05.2": {
    title_tr: "Akut periodontit",
    title_en: "Aggressive periodontitis",
    title_ka: "აგრესიული პერიოდონტიტი",
    title_ru: "Агрессивный периодонтит",
    description_tr: "Hızlı ilerleyen periodontal hastalık",
    description_en: "Rapidly progressive periodontal disease",
    description_ka: "სწრაფად პროგრესირებადი პერიოდონტული დაავადება",
    description_ru: "Быстро прогрессирующее периодонтальное заболевание",
  },
  "K06.0": {
    title_tr: "Gingival retraksiyon",
    title_en: "Gingival recession",
    title_ka: "გინგივალური რეცესია",
    title_ru: "Рецессия десны",
    description_tr: "Diş eti çekilmesi",
    description_en: "Recession of gingiva",
    description_ka: "გინგივის რეცესია",
    description_ru: "Рецессия десны",
  },
  "K06.1": {
    title_tr: "Gingival hiperplazi",
    title_en: "Gingival hyperplasia",
    title_ka: "გინგივალური ჰიპერპლაზია",
    title_ru: "Гиперплазия десны",
    description_tr: "Diş eti büyümesi",
    description_en: "Overgrowth of gingiva",
    description_ka: "გინგივის ზრდა",
    description_ru: "Разрастание десны",
  },
  "K07.0": {
    title_tr: "Anormal kapanış",
    title_en: "Major malocclusion",
    title_ka: "მთავარი მალოკლუზია",
    title_ru: "Основная аномалия прикуса",
    description_tr: "Çene kapanış bozukluğu",
    description_en: "Major anomalies of jaw size",
    description_ka: "კბილების ზომის მთავარი ანომალიები",
    description_ru: "Основные аномалии размера челюсти",
  },
  "K08.1": {
    title_tr: "Diş kırığı",
    title_en: "Fracture of tooth",
    title_ka: "კბილის მოტეხვა",
    title_ru: "Перелом зуба",
    description_tr: "Dişin kırılması",
    description_en: "Fracture of tooth",
    description_ka: "კბილის მოტეხვა",
    description_ru: "Перелом зуба",
  },
  "K08.2": {
    title_tr: "Diş kaybı",
    title_en: "Atrophy of edentulous alveolar ridge",
    title_ka: "უკბილო ალვეოლური ქედის ატროფია",
    title_ru: "Атрофия беззубого альвеолярного гребня",
    description_tr: "Dişsiz kemik erimesi",
    description_en: "Atrophy of alveolar ridge",
    description_ka: "ალვეოლური ქედის ატროფია",
    description_ru: "Атрофия альвеолярного гребня",
  },
  "K09.0": {
    title_tr: "Radiküler kist",
    title_en: "Developmental odontogenic cysts",
    title_ka: "დეველოპმენტური ოდონტოგენური კისტები",
    title_ru: "Развивающиеся одонтогенные кисты",
    description_tr: "Gelişimsel diş kistleri",
    description_en: "Developmental odontogenic cysts",
    description_ka: "დეველოპმენტური ოდონტოგენური კისტები",
    description_ru: "Развивающиеся одонтогенные кисты",
  },
  "K10.0": {
    title_tr: "Çene kisti",
    title_en: "Disorders of development of jaws",
    title_ka: "კბილების განვითარების აშლილობები",
    title_ru: "Нарушения развития челюстей",
    description_tr: "Çene gelişim bozuklukları",
    description_en: "Disorders of development of jaws",
    description_ka: "კბილების განვითარების აშლილობები",
    description_ru: "Нарушения развития челюстей",
  },
  "K11.0": {
    title_tr: "Sialolitiazis",
    title_en: "Atrophy of salivary glands",
    title_ka: "სალივარიული ჯირულების ატროფია",
    title_ru: "Атрофия слюнных желез",
    description_tr: "Tükrük bezi taşları",
    description_en: "Sialolithiasis",
    description_ka: "სიალოლითიაზი",
    description_ru: "Сиалолитиаз",
  },
  "K12.0": {
    title_tr: "Aftöz stomatit",
    title_en: "Recurrent oral aphthae",
    title_ka: "რეციდივირებადი ორალური აფთები",
    title_ru: "Рецидивирующий афтозный стоматит",
    description_tr: "Aftlar",
    description_en: "Recurrent oral aphthae",
    description_ka: "რეციდივირებადი ორალური აფთები",
    description_ru: "Рецидивирующий афтозный стоматит",
  },
  "K13.0": {
    title_tr: "Lezyon",
    title_en: "Diseases of lips",
    title_ka: "ტუჩების დაავადებები",
    title_ru: "Заболевания губ",
    description_tr: "Dudak hastalıkları",
    description_en: "Diseases of lips",
    description_ka: "ტუჩების დაავადებები",
    description_ru: "Заболевания губ",
  },
  "K14.0": {
    title_tr: "Dil lezyonu",
    title_en: "Glossodynia",
    title_ka: "გლოსოდინია",
    title_ru: "Глоссодиния",
    description_tr: "Dil ağrısı",
    description_en: "Glossodynia",
    description_ka: "გლოსოდინია",
    description_ru: "Глоссодиния",
  },
};

/**
 * Merge canonical labels for known dental codes so API + clients get title_* per language
 * even when Supabase only has English category/description.
 */
function fillIcdRowFromStatic(row) {
  if (!row || typeof row !== "object") return row;
  const code = String(row.code || row.icd10_code || "").trim();
  if (!code) return row;
  const fill = BY_CODE[code];
  if (!fill) return row;
  return { ...row, ...fill };
}

module.exports = { fillIcdRowFromStatic, BY_CODE };
