-- AI operational visit plan drafts (tentative timelines — not confirmed appointments).

CREATE TABLE IF NOT EXISTS public.ai_visit_plan_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
  patient_id uuid,
  lead_profile_id uuid REFERENCES public.ai_coordinator_lead_profiles(id) ON DELETE SET NULL,
  session_id text,
  treatment_type text,
  proposed_visit_count integer,
  estimated_stay_duration text,
  draft_timeline_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  ai_summary text,
  coordinator_notes text,
  status text NOT NULL DEFAULT 'draft',
  generated_at timestamptz NOT NULL DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_visit_plan_drafts_status_check
    CHECK (status IN ('draft', 'reviewed', 'approved', 'archived')),
  CONSTRAINT ai_visit_plan_drafts_visit_count_nonneg CHECK (
    proposed_visit_count IS NULL OR proposed_visit_count >= 1
  )
);

CREATE INDEX IF NOT EXISTS ai_visit_plan_drafts_clinic_status_idx
  ON public.ai_visit_plan_drafts (clinic_id, status, generated_at DESC);

CREATE INDEX IF NOT EXISTS ai_visit_plan_drafts_lead_profile_idx
  ON public.ai_visit_plan_drafts (lead_profile_id, generated_at DESC)
  WHERE lead_profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ai_visit_plan_drafts_session_idx
  ON public.ai_visit_plan_drafts (session_id, generated_at DESC)
  WHERE session_id IS NOT NULL;

COMMENT ON TABLE public.ai_visit_plan_drafts IS
  'Tentative operational visit timelines generated by AI — coordinator review before any scheduling.';

-- Timeline event type for visit plan drafts.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ai_coordinator_lead_events_event_type_check'
  ) THEN
    ALTER TABLE public.ai_coordinator_lead_events
      DROP CONSTRAINT ai_coordinator_lead_events_event_type_check;
  END IF;
END $$;

ALTER TABLE public.ai_coordinator_lead_events
  ADD CONSTRAINT ai_coordinator_lead_events_event_type_check
  CHECK (event_type IN (
    'patient_turn', 'ai_reply', 'human_takeover', 'human_reply',
    'coordination_change', 'escalation_detected', 'follow_up_scheduled',
    'appointment_intent', 'task_created', 'visit_plan_drafted', 'system'
  ));
