-- Clinifly Partner Clinic Playbook — clinic onboarding, acquisition, objection handling.
-- Canonical data: lib/cliniflyPartnerClinicPlaybookData.js
-- Re-emit: node scripts/seed-partner-clinic-playbook.cjs --emit-sql

CREATE TABLE IF NOT EXISTS clinifly_partner_clinic_playbook_entries (
  id text PRIMARY KEY,
  section text NOT NULL CHECK (section IN (
    'patient_acquisition',
    'international_dental_tourism',
    'ai_assistant',
    'clinic_profile_marketplace',
    'referral_system',
    'pricing_membership',
    'objection_handling'
  )),
  intent text NOT NULL,
  question text NOT NULL,
  question_aliases text[] NOT NULL DEFAULT '{}',
  short_answer text NOT NULL,
  detailed_answer text,
  language text NOT NULL DEFAULT 'en' CHECK (language IN ('en', 'ka', 'tr', 'ru')),
  priority int NOT NULL DEFAULT 50,
  sort_order int NOT NULL DEFAULT 0,
  tags text[] NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  version int NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE clinifly_partner_clinic_playbook_entries IS
  'Clinifly Partner Clinic Playbook — sales-oriented FAQ for clinic onboarding and partnership conversations.';

CREATE INDEX IF NOT EXISTS idx_clinifly_playbook_lang
  ON clinifly_partner_clinic_playbook_entries (language)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_clinifly_playbook_section
  ON clinifly_partner_clinic_playbook_entries (section, sort_order)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_clinifly_playbook_intent
  ON clinifly_partner_clinic_playbook_entries (intent)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_clinifly_playbook_tags
  ON clinifly_partner_clinic_playbook_entries USING gin (tags);

-- Auto-generated from lib/cliniflyPartnerClinicPlaybookData.js
-- Auto-generated from lib/cliniflyPartnerClinicPlaybookData.js
INSERT INTO clinifly_partner_clinic_playbook_entries (
  id, section, intent, question, question_aliases, short_answer, detailed_answer, language, priority, sort_order, tags
) VALUES
(
  'playbook.en.001',
  'patient_acquisition',
  'get_more_patients',
  'How does Clinifly help me get more patients?',
  ARRAY['How will Clinifly bring more patients to my dental clinic?', 'Can Clinifly help us get more patient inquiries?', 'How can Clinifly support clinic growth?'],
  'Clinifly helps patients discover your clinic, contact you directly, and get fast answers — so more inquiries can turn into appointments.',
  'Most clinics lose patients when replies are slow or messages are missed. Clinifly helps you get more patient inquiries, answer 24/7 on WhatsApp, Messenger, and Clinifly, and follow up clearly. Your team spends less time on repetitive questions and more time booking real appointments. Results depend on your clinic and market — we do not guarantee a fixed number of patients.',
  'en',
  98,
  1,
  ARRAY['growth', 'new_patients', 'appointments', 'faster_replies']
),
(
  'playbook.en.002',
  'patient_acquisition',
  'platform_positioning',
  'What is Clinifly in one sentence for dental clinics?',
  ARRAY['How should we explain Clinifly to our team?', 'What does Clinifly do for a clinic?', 'What is Clinifly in one line?'],
  'A system that helps clinics attract patients, respond faster, communicate in multiple languages, and convert more inquiries into appointments.',
  'If you need one simple explanation, use this: Clinifly helps clinics get more patient inquiries and turn those inquiries into booked visits. It supports quick answers, 24/7 conversations, and communication in more than 20 languages so local and international patients can speak comfortably.',
  'en',
  97,
  2,
  ARRAY['positioning', 'overview', 'clear_message', 'value']
),
(
  'playbook.en.003',
  'patient_acquisition',
  'visibility_improvement',
  'How does Clinifly improve clinic visibility?',
  ARRAY['How can Clinifly make our clinic easier to find?', 'Does Clinifly increase online visibility?', 'Can Clinifly help more patients notice us?'],
  'Clinifly helps more patients discover your clinic and contact you directly.',
  'When your clinic profile is clear and contact is easy, more patients take action. Clinifly helps patients find your clinic, review key details, and start messaging right away. Better visibility plus fast communication means more real inquiries, not just profile views.',
  'en',
  96,
  3,
  ARRAY['visibility', 'discovery', 'patient_inquiries', 'contact']
),
(
  'playbook.en.004',
  'patient_acquisition',
  'digital_channel_advantage',
  'What makes Clinifly different from Google, Facebook, or Instagram?',
  ARRAY['Why not just use Google and social media?', 'How is Clinifly different from only running ads?', 'Is Clinifly more than social channels?'],
  'Google and social apps help people notice you; Clinifly helps you reply faster and turn more messages into appointments.',
  'Ads and social content can bring attention, but clinics still need fast and consistent patient communication. Clinifly helps with that next step by keeping conversations active 24/7 and guiding patients toward booking. So it is not just about getting messages, it is about converting those messages into visits.',
  'en',
  95,
  4,
  ARRAY['google', 'facebook', 'instagram', 'conversion']
),
(
  'playbook.en.005',
  'patient_acquisition',
  'new_platform_reason',
  'Why should I join another platform?',
  ARRAY['Why should our clinic add Clinifly?', 'Do we really need one more tool?', 'What is the business reason to join Clinifly?'],
  'Because Clinifly helps your team answer faster, reduce chat workload, and book more appointments from existing inquiries.',
  'Many clinics already receive messages, but slow replies and missed follow-up reduce bookings. Clinifly helps you respond quickly, continue conversations, and request needed details such as photos. That means your staff spends less time repeating the same answers and more time on real patients.',
  'en',
  94,
  5,
  ARRAY['why_join', 'faster_response', 'less_workload', 'more_bookings']
),
(
  'playbook.en.006',
  'patient_acquisition',
  'inquiry_to_appointment',
  'How does Clinifly help turn patient inquiries into appointments?',
  ARRAY['Can Clinifly convert messages into booked visits?', 'We get messages but struggle to book — can Clinifly help?', 'Does Clinifly help with inquiry to appointment conversion?'],
  'Our goal is not only to receive messages, but to help convert patient inquiries into appointments — with fast replies, clear answers, and follow-up your team can continue.',
  'Many clinics receive inquiries but lose them when follow-up is slow or unclear. Clinifly answers patient questions quickly, asks for photos when needed, shares treatment information, and keeps the chat active 24/7. Your team can step in anytime to close the booking. This improves your chance of turning interest into a real appointment — without promising a fixed number of bookings.',
  'en',
  93,
  6,
  ARRAY['inquiries', 'follow_up', 'appointment_goal', 'staff_support']
),
(
  'playbook.en.007',
  'patient_acquisition',
  'brand_trust_conversion',
  'Can Clinifly help us look more professional to new patients?',
  ARRAY['Will Clinifly improve first impressions?', 'Can we build more trust with new patients?', 'Does presentation affect appointment decisions?'],
  'Yes. Patients see faster, clearer communication, which builds trust from the first message.',
  'Patients decide quickly which clinic feels reliable. When they get clear answers right away, confidence goes up. Clinifly helps your clinic keep that quality in every first conversation, including nights and weekends, so more patients continue to the booking stage.',
  'en',
  92,
  7,
  ARRAY['trust', 'first_impression', 'professional_image', 'booking']
),
(
  'playbook.en.008',
  'patient_acquisition',
  'multilingual_communication',
  'Can Clinifly communicate with patients in different languages?',
  ARRAY['Does Clinifly support multiple languages?', 'Can international patients message in their own language?', 'How many languages does Clinifly AI speak?'],
  'Clinifly AI can communicate with patients in more than 20 languages, helping clinics work with international patients without language barriers.',
  'Language is often the first barrier for international patients. Clinifly AI replies in the language the patient uses — including English, Turkish, Russian, Arabic, Georgian, and many others — so your clinic can respond quickly without hiring multilingual staff for every shift. Local patients benefit from the same fast replies.',
  'en',
  91,
  8,
  ARRAY['local_patients', 'international_patients', 'multi_language', 'growth']
),
(
  'playbook.en.009',
  'international_dental_tourism',
  'international_discovery',
  'How do international patients find my clinic?',
  ARRAY['How can foreign patients discover our clinic?', 'How does Clinifly connect us with international patients?', 'Where do overseas dental patients find clinics?'],
  'Clinifly helps international patients discover your clinic and contact you directly.',
  'Patients traveling for treatment usually compare clinics online before choosing. Clinifly helps your clinic appear clearly and makes it easy to start a conversation immediately. Fast replies in the patient''s language help keep their interest strong.',
  'en',
  90,
  9,
  ARRAY['international', 'discovery', 'dental_tourism', 'direct_contact']
),
(
  'playbook.en.010',
  'international_dental_tourism',
  'dental_tourism_support',
  'How can Clinifly help with dental tourism?',
  ARRAY['What does Clinifly do for dental tourism clinics?', 'Can Clinifly support cross-border treatment inquiries?', 'How does Clinifly help before patients travel?'],
  'Clinifly helps international patients ask questions, send photos, and get treatment information before they travel.',
  'Dental tourism patients need more pre-travel communication than local patients. Clinifly helps your clinic answer questions, gather photos, and explain next steps clearly. This creates smoother planning and helps move more inquiries to confirmed appointments.',
  'en',
  89,
  10,
  ARRAY['dental_tourism', 'pre_travel', 'photos', 'appointments']
),
(
  'playbook.en.011',
  'international_dental_tourism',
  'foreign_contact_channels',
  'How do foreign patients contact my clinic?',
  ARRAY['How can overseas patients message us easily?', 'What channels do international patients use to reach clinics?', 'How does Clinifly simplify contact for foreign patients?'],
  'They can message your clinic through familiar apps like WhatsApp and Messenger, with fast replies from Clinifly AI.',
  'International patients often use messaging apps first. Clinifly helps your clinic answer from WhatsApp, Messenger, and Clinifly 24/7, so patients do not wait. Quick first contact increases the chance they continue to appointment planning.',
  'en',
  88,
  11,
  ARRAY['whatsapp', 'messenger', 'international_contact', '24_7']
),
(
  'playbook.en.012',
  'international_dental_tourism',
  'cross_border_requests',
  'How can I receive treatment requests from other countries?',
  ARRAY['Can Clinifly bring treatment inquiries from abroad?', 'How do we get dental case requests internationally?', 'How does Clinifly help with overseas requests?'],
  'Clinifly helps more international patients find your clinic and start treatment conversations quickly.',
  'To receive requests from abroad, your clinic must be easy to discover and easy to contact. Clinifly supports both, then helps continue the chat with fast answers and clear next steps. This keeps international inquiries active and improves appointment potential.',
  'en',
  87,
  12,
  ARRAY['overseas_requests', 'international_growth', 'quick_replies', 'treatment_info']
),
(
  'playbook.en.013',
  'international_dental_tourism',
  'international_trust_building',
  'How does Clinifly help build trust with international patients?',
  ARRAY['Can Clinifly make foreign patients feel more confident?', 'How do we reduce hesitation from overseas patients?', 'Does better communication improve international trust?'],
  'Fast, clear replies in the patient''s language help build trust before travel.',
  'Patients traveling from another country need confidence before booking. Clinifly helps your clinic answer quickly, explain treatment options clearly, and keep the conversation active. Communication in 20+ languages removes language barriers and helps patients feel understood.',
  'en',
  86,
  13,
  ARRAY['trust', 'language_support', 'international_confidence', 'clear_answers']
),
(
  'playbook.en.014',
  'international_dental_tourism',
  'tourism_process_clarity',
  'Can Clinifly make dental tourism communication more organized?',
  ARRAY['How can we keep international inquiries clear?', 'Can Clinifly reduce confusion in cross-border communication?', 'Does Clinifly help us manage tourism conversations?'],
  'Yes. Clinifly keeps international conversations clearer and easier for your team to handle.',
  'Dental tourism chats often include many questions over several days. Clinifly helps continue these conversations without losing context, so patients get clear answers and your team spends less time repeating details. Clear communication leads to smoother appointment decisions.',
  'en',
  85,
  14,
  ARRAY['dental_tourism', 'clear_communication', 'less_confusion', 'staff_support']
),
(
  'playbook.en.015',
  'international_dental_tourism',
  'international_patient_growth',
  'Is Clinifly suitable if we want more international patients?',
  ARRAY['Can Clinifly support a clinic focused on foreign patients?', 'Is Clinifly useful for dental tourism growth?', 'Can we use Clinifly to get more overseas inquiries?'],
  'Yes. Clinifly is built to help clinics attract and serve more international patients.',
  'If your clinic wants more patients from abroad, you need quick replies, language support, and clear communication before they travel. Clinifly helps with all three. International patients can ask questions, send photos, and receive information 24/7 — giving your team a better chance to book appointments.',
  'en',
  84,
  15,
  ARRAY['international_patients', 'dental_tourism_growth', 'language', 'appointments']
),
(
  'playbook.en.016',
  'international_dental_tourism',
  'international_inquiry_quality',
  'How does Clinifly improve the quality of international patient inquiries?',
  ARRAY['Can Clinifly help us get more serious overseas inquiries?', 'How do we improve international inquiry quality?', 'Does Clinifly help us qualify foreign inquiries?'],
  'Clinifly helps patients share better details early, so your team can focus on stronger inquiries.',
  'Inquiry quality improves when patients get clear guidance from the first message. Clinifly AI can ask useful questions, request photos, and share treatment information before handover to your team. This gives staff better context and saves time on low-intent chats.',
  'en',
  83,
  16,
  ARRAY['inquiry_quality', 'photo_request', 'better_context', 'international']
),
(
  'playbook.en.017',
  'ai_assistant',
  'ai_assistant_role',
  'What does the AI assistant do?',
  ARRAY['What is the main job of Clinifly AI assistant?', 'How does the AI assistant help our clinic team?', 'What tasks can the assistant handle?'],
  'It answers patient questions, asks for photos, shares treatment information, and continues chats 24/7.',
  'Clinifly AI handles the first part of many patient conversations. It replies instantly, gives helpful information, and keeps patients engaged while your team is busy or offline. Your staff can step in at any time when a personal conversation is needed.',
  'en',
  82,
  17,
  ARRAY['ai_assistant', '24_7_replies', 'photos', 'treatment_information']
),
(
  'playbook.en.018',
  'ai_assistant',
  'messaging_channel_coverage',
  'Can it answer WhatsApp and Messenger messages?',
  ARRAY['Does Clinifly AI work on WhatsApp?', 'Can the assistant reply on Facebook Messenger too?', 'Will AI support both channels automatically?'],
  'Yes. Clinifly can answer patient messages from WhatsApp, Messenger, and Clinifly 24/7, helping you turn more inquiries into appointments.',
  'Most patients message where they are already comfortable. Clinifly AI responds on WhatsApp and Messenger right away, so no patient waits for office hours. This faster first reply helps protect interest and improves booking chances.',
  'en',
  81,
  18,
  ARRAY['whatsapp', 'messenger', 'fast_response', 'bookings']
),
(
  'playbook.en.019',
  'ai_assistant',
  'human_takeover',
  'Can my team take over conversations?',
  ARRAY['Can staff step in when needed?', 'Do humans stay in control of AI chats?', 'Can coordinators continue the conversation directly?'],
  'Yes. Your team can join or take over any conversation whenever they want.',
  'Clinifly AI supports your staff, it does not replace them. Team members can jump into a chat at any point and continue with a personal touch. This gives you both speed from AI and full control from your team.',
  'en',
  80,
  19,
  ARRAY['human_handover', 'team_control', 'personal_care', 'ai_support']
),
(
  'playbook.en.020',
  'ai_assistant',
  'ai_training_sources',
  'How is the AI trained?',
  ARRAY['Where does Clinifly AI learn clinic answers from?', 'Can the assistant reflect our clinic messaging style?', 'Is AI trained for dental patient conversations?'],
  'It is trained for dental clinic conversations so answers stay clear, helpful, and patient-friendly.',
  'Clinifly AI is prepared to handle common dental inquiry topics, including treatment questions and pre-appointment details. It aims to give simple and consistent answers that match clinic communication needs. Clinical decisions still stay with dentists and your team.',
  'en',
  79,
  20,
  ARRAY['ai_training', 'clear_answers', 'dental_context', 'consistency']
),
(
  'playbook.en.021',
  'ai_assistant',
  'response_consistency',
  'How does the AI keep answers consistent and professional?',
  ARRAY['Can AI maintain the same quality in every patient reply?', 'Will Clinifly AI protect our communication standards?', 'How do we avoid inconsistent staff responses?'],
  'Clinifly AI gives clear and consistent first replies, even when message volume is high.',
  'During busy hours, reply quality can drop when staff are overloaded. Clinifly AI keeps a stable tone and answers common questions instantly, so patients always receive prompt and clear communication. Your team can then focus on detailed case discussions.',
  'en',
  78,
  21,
  ARRAY['consistent_replies', 'professional_tone', 'busy_hours', 'patient_experience']
),
(
  'playbook.en.022',
  'ai_assistant',
  'after_hours_ai_coverage',
  'Can the AI respond when our clinic is closed?',
  ARRAY['Does Clinifly AI work after hours?', 'Can we answer patients outside office times?', 'Will inquiries wait until morning without Clinifly?'],
  'Yes. Clinifly AI can answer patient messages 24/7, even when your clinic is closed.',
  'Many patients message at night or from different time zones. Clinifly AI replies immediately, so interest is not lost while your team is offline. By morning, your staff can continue active conversations instead of starting from zero.',
  'en',
  77,
  22,
  ARRAY['after_hours', '24_7', 'timezone_support', 'active_inquiries']
),
(
  'playbook.en.023',
  'ai_assistant',
  'ai_and_team_efficiency',
  'How does AI improve our team''s daily workload?',
  ARRAY['Can Clinifly reduce repetitive front-desk messaging?', 'Will AI free up our coordinators'' time?', 'How does AI reduce staff workload?'],
  'Patients receive answers immediately, while your staff spends less time answering repetitive questions.',
  'Front-desk teams often repeat the same answers all day — prices, hours, treatment basics. Clinifly AI handles those first messages, requests photos, and shares treatment information 24/7. Your staff steps in when a personal conversation is needed. Less repetitive work, more time for patients ready to book.',
  'en',
  76,
  23,
  ARRAY['staff_workload', 'repetitive_questions', 'time_saving', 'appointment_focus']
),
(
  'playbook.en.024',
  'clinic_profile_marketplace',
  'list_on_clinifly_reason',
  'Why should I list my clinic on Clinifly?',
  ARRAY['What is the benefit of listing our clinic profile?', 'Why does clinic listing matter on Clinifly?', 'Will listing help us get more inquiries?'],
  'Listing helps patients discover your clinic and message you directly.',
  'A clear listing gives patients a quick way to understand your clinic and start a conversation. This shortens the path from interest to inquiry. More visibility plus direct contact can lead to more appointment opportunities.',
  'en',
  75,
  24,
  ARRAY['clinic_listing', 'patient_discovery', 'direct_messages', 'inquiries']
),
(
  'playbook.en.025',
  'clinic_profile_marketplace',
  'complete_profile_importance',
  'Why should I complete my clinic profile?',
  ARRAY['Does a complete profile really make a difference?', 'How important is profile completeness for inquiries?', 'Should we fill all clinic profile details?'],
  'A complete profile builds trust and encourages more patients to contact your clinic.',
  'Patients compare clinics quickly. If your profile answers common questions, people feel safer contacting you. Complete details can improve inquiry quality because patients already understand your clinic before they message.',
  'en',
  74,
  25,
  ARRAY['complete_profile', 'patient_trust', 'better_inquiries', 'clinic_info']
),
(
  'playbook.en.026',
  'clinic_profile_marketplace',
  'profile_content_impact',
  'How do reviews, social media links, doctors, and photos help?',
  ARRAY['Do profile details like photos and doctor info increase trust?', 'Why should we add reviews and social links?', 'How does rich profile content help patient decisions?'],
  'These details help patients trust your clinic and contact you faster.',
  'Reviews, photos, and doctor information reduce patient hesitation. People feel more confident when they can see your clinic clearly before sending a message. Higher trust usually means more conversations and better appointment intent.',
  'en',
  73,
  26,
  ARRAY['reviews', 'doctor_info', 'photos', 'trust_signals']
),
(
  'playbook.en.027',
  'clinic_profile_marketplace',
  'marketplace_competitive_edge',
  'How does a Clinifly profile help us compete with other clinics?',
  ARRAY['Can Clinifly profile quality improve competitiveness?', 'How do we stand out in a crowded dental market?', 'Will a better profile help us win patient attention?'],
  'A stronger profile helps your clinic stand out and get more patient messages.',
  'When patients compare options, they usually choose the clinic that looks clear, responsive, and trustworthy. Clinifly helps present your clinic in a simple and convincing way. Better first impression can lead to more direct inquiries.',
  'en',
  72,
  27,
  ARRAY['competition', 'stand_out', 'profile_quality', 'patient_attention']
),
(
  'playbook.en.028',
  'clinic_profile_marketplace',
  'profile_update_frequency',
  'How often should we update our clinic profile?',
  ARRAY['Should we refresh photos and clinic info regularly?', 'Does profile freshness affect patient interest?', 'When should we revise our listing content?'],
  'Update your profile regularly so patients always see current and accurate information.',
  'Old information can reduce trust and create confusion. Regular updates to photos, team details, and services show that your clinic is active. Fresh information helps patients decide faster and message with confidence.',
  'en',
  71,
  28,
  ARRAY['profile_updates', 'accuracy', 'fresh_content', 'patient_confidence']
),
(
  'playbook.en.029',
  'clinic_profile_marketplace',
  'marketplace_visibility_growth',
  'Can Clinifly marketplace presence increase our inquiry volume?',
  ARRAY['Will being visible in Clinifly bring more patient interest?', 'Does marketplace placement help generate inquiries?', 'Can profile visibility improve inquiry flow?'],
  'It can increase inquiry volume by helping more patients discover and contact your clinic.',
  'Results depend on your market and clinic offer, but better visibility usually creates more chances for patient contact. Clinifly helps turn profile views into real messages by making communication easy. The focus is always more inquiries and more appointments.',
  'en',
  70,
  29,
  ARRAY['marketplace_visibility', 'inquiry_volume', 'patient_interest', 'appointments']
),
(
  'playbook.en.030',
  'clinic_profile_marketplace',
  'profile_to_conversation_path',
  'How does Clinifly connect profile visitors to real conversations?',
  ARRAY['How do patients move from profile view to contact?', 'Can profile traffic convert into chat inquiries?', 'Does Clinifly shorten the path to contact?'],
  'Clinifly makes it easy for profile visitors to start a chat immediately.',
  'Patients often drop off when contact takes too many steps. Clinifly reduces that delay by linking clinic discovery to instant messaging options. This helps more interested visitors become active inquiries.',
  'en',
  69,
  30,
  ARRAY['profile_to_chat', 'easy_contact', 'fewer_dropoffs', 'inquiry_conversion']
),
(
  'playbook.en.031',
  'referral_system',
  'referral_system_overview',
  'How does the referral system work?',
  ARRAY['How does Clinifly referral flow operate?', 'Can patients invite others through Clinifly?', 'How are referrals tracked for clinics?'],
  'Clinifly helps your clinic turn happy patients into new patient inquiries through referrals.',
  'Referrals are one of the strongest trust sources for clinics. Clinifly helps make referral activity clearer and easier to follow, so your team can respond quickly. This can bring steady new inquiries from patient recommendations.',
  'en',
  68,
  31,
  ARRAY['referrals', 'happy_patients', 'new_inquiries', 'trust']
),
(
  'playbook.en.032',
  'referral_system',
  'existing_patients_acquisition',
  'How can existing patients help attract new patients?',
  ARRAY['Can current patients drive clinic growth?', 'How do we use patient satisfaction for referrals?', 'How does Clinifly support patient recommendations?'],
  'Satisfied patients can recommend your clinic, and Clinifly helps you handle those referrals better.',
  'People trust recommendations from friends and family. Clinifly helps your clinic keep referral conversations active and respond quickly. This helps convert referred inquiries into appointments with less delay.',
  'en',
  67,
  32,
  ARRAY['existing_patients', 'recommendations', 'referral_growth', 'appointments']
),
(
  'playbook.en.033',
  'referral_system',
  'referral_conversion_quality',
  'Are referrals usually higher quality than cold leads?',
  ARRAY['Do referred patients convert better?', 'Why are referrals valuable for dental clinics?', 'Should we prioritize referral-driven growth?'],
  'Often yes, because referred patients usually come with higher trust from the start.',
  'Referral patients usually arrive warmer than unknown leads. Clinifly helps your team answer these inquiries quickly and move them toward booking. Fast follow-up is still important to convert trust into real appointments.',
  'en',
  66,
  33,
  ARRAY['referral_quality', 'higher_trust', 'faster_follow_up', 'bookings']
),
(
  'playbook.en.034',
  'referral_system',
  'referral_tracking_visibility',
  'Can we track referral performance inside Clinifly?',
  ARRAY['How do we measure referrals with Clinifly?', 'Can we see which referral activity brings results?', 'Does Clinifly make referrals measurable?'],
  'Yes. Clinifly helps your team see referral activity more clearly.',
  'When referral activity is visible, your clinic can learn what is working and improve over time. Clinifly helps keep referral conversations easier to review so your team can make better decisions. This supports steady, repeatable referral growth.',
  'en',
  65,
  34,
  ARRAY['referral_tracking', 'measurement', 'better_decisions', 'growth']
),
(
  'playbook.en.035',
  'referral_system',
  'referrals_with_other_channels',
  'Can referrals work together with our other patient acquisition channels?',
  ARRAY['Should referrals be combined with ads and social?', 'Can Clinifly manage referrals and inbound inquiries together?', 'Is referral growth part of a full acquisition strategy?'],
  'Yes. Referrals work best alongside WhatsApp, social media, and other ways patients find you.',
  'Strong clinics usually grow from more than one source. Clinifly helps your clinic answer referral and non-referral messages with the same fast replies. That means fewer missed conversations and more chances to book appointments.',
  'en',
  64,
  35,
  ARRAY['referrals_plus_ads', 'balanced_growth', 'inquiry_sources', 'clinic_strategy']
),
(
  'playbook.en.036',
  'pricing_membership',
  'free_registration',
  'Is Clinifly free?',
  ARRAY['Can I register my clinic for free?', 'Do we pay anything to start?', 'Is there a free starting option for clinics?'],
  'Yes. Clinic registration is free, with a 2-month trial and no credit card required.',
  'You can sign up your clinic for free and test Clinifly for two months before paying. No credit card is needed to start the trial. This lets your team evaluate results in real patient conversations with low risk.',
  'en',
  63,
  36,
  ARRAY['free_registration', 'two_month_trial', 'no_credit_card', 'low_risk_start']
),
(
  'playbook.en.037',
  'pricing_membership',
  'included_features',
  'What features are included?',
  ARRAY['What do clinics get with Clinifly?', 'Which core tools are included?', 'What is included in the clinic plan?'],
  'Clinifly helps clinics attract patients, answer inquiries quickly, and convert more inquiries into appointments.',
  'Core value includes patient discovery, direct messaging, AI assistant support, and team handover when needed. Clinifly also supports communication in more than 20 languages for international patients. The main goal is simple: more inquiries, faster replies, and more appointment conversions.',
  'en',
  62,
  37,
  ARRAY['included_features', 'ai_assistant', 'multi_language', 'appointment_conversion']
),
(
  'playbook.en.038',
  'pricing_membership',
  'future_paid_plans',
  'Are there future paid plans?',
  ARRAY['Will Clinifly have paid tiers after trial?', 'What are the plans after the free period?', 'Is there a paid clinic plan after trial?'],
  'Yes. After trial, clinics can continue with paid plans like Pro and Premium.',
  'Clinics start free, test for two months, then choose the plan that fits their needs. This gives teams time to see real value before paying. It is a simple path from trial to paid use.',
  'en',
  61,
  38,
  ARRAY['paid_plans', 'pro_plan', 'premium_plan', 'post_trial']
),
(
  'playbook.en.039',
  'pricing_membership',
  'trial_details',
  'How long is the trial, and do I need a card?',
  ARRAY['Is the trial 2 months?', 'Do clinics need credit card details for trial activation?', 'Can we test Clinifly before paying?'],
  'The trial is 2 months, and you do not need a credit card.',
  'Your clinic can use Clinifly for two full months to test response speed, staff workload impact, and appointment conversion results. No card is required to begin. This keeps your decision simple and low risk.',
  'en',
  60,
  39,
  ARRAY['trial_length', 'no_card_needed', 'test_before_pay', 'clinic_trial']
),
(
  'playbook.en.040',
  'pricing_membership',
  'pro_plan_price',
  'What is the Pro plan price?',
  ARRAY['How much is Clinifly Pro per month?', 'Is Pro $29 monthly?', 'What does the entry paid plan cost?'],
  'Clinifly Pro is $29 per month (USD).',
  'After the trial, clinics can choose Pro for $29/month USD. It is a simple next step for teams that want to continue using Clinifly to handle inquiries and improve appointment conversion.',
  'en',
  59,
  40,
  ARRAY['pro_price', '29_usd', 'monthly_plan', 'pricing']
),
(
  'playbook.en.041',
  'pricing_membership',
  'premium_plan_price',
  'What is the Premium plan price?',
  ARRAY['How much is Clinifly Premium monthly?', 'Is Premium $89 per month?', 'What does the higher plan cost?'],
  'Clinifly Premium is $89 per month (USD).',
  'Clinics that need more capacity can choose Premium for $89/month USD after trial. This gives a clear upgrade path as your inquiry volume and team needs grow.',
  'en',
  58,
  41,
  ARRAY['premium_price', '89_usd', 'upgrade_plan', 'pricing']
),
(
  'playbook.en.042',
  'pricing_membership',
  'patient_app_cost',
  'Are patient apps free?',
  ARRAY['Do patients pay to use Clinifly app?', 'Is the patient mobile app free to download?', 'Are patient-facing apps included at no cost?'],
  'Yes. Patient apps are free, while clinics use trial and paid plans.',
  'Patients can use the app without paying, which makes it easier for them to communicate with clinics. Clinics follow the free registration plus trial and paid plan structure. This supports easier patient adoption and clear clinic pricing.',
  'en',
  57,
  42,
  ARRAY['patient_apps_free', 'clinic_plans', 'clear_pricing', 'adoption']
),
(
  'playbook.en.043',
  'objection_handling',
  'already_use_whatsapp',
  'I already use WhatsApp.',
  ARRAY['We already chat with patients on WhatsApp, why Clinifly?', 'If WhatsApp works, what extra value does Clinifly add?', 'Do we need Clinifly if we already use WhatsApp daily?'],
  'WhatsApp gives messages; Clinifly helps you answer faster and turn more of those messages into appointments.',
  'Using WhatsApp is good, but many clinics still lose inquiries because replies are delayed or inconsistent. Clinifly AI can answer 24/7, keep chats active, and let your team take over anytime. This helps reduce missed opportunities without changing patient behavior.',
  'en',
  56,
  43,
  ARRAY['objection', 'whatsapp', 'faster_replies', 'more_appointments']
),
(
  'playbook.en.044',
  'objection_handling',
  'already_use_instagram',
  'I already have Instagram.',
  ARRAY['We already market on Instagram, do we still need Clinifly?', 'If we get DMs from Instagram, what does Clinifly add?', 'Can Clinifly improve inquiry handling from social media?'],
  'Instagram can create interest; Clinifly helps convert that interest into appointments.',
  'Social media can bring patient messages, but booking depends on fast and clear follow-up. Clinifly helps continue those conversations right away, including after hours. This improves your chance of turning DMs into confirmed visits.',
  'en',
  55,
  44,
  ARRAY['objection', 'instagram', 'social_messages', 'appointment_conversion']
),
(
  'playbook.en.045',
  'objection_handling',
  'already_get_google_patients',
  'I already get patients from Google.',
  ARRAY['If Google already works for us, why use Clinifly?', 'Do we need Clinifly when search brings inquiries?', 'Can Clinifly improve conversion of existing Google inquiries?'],
  'Clinifly helps you get more value from Google inquiries by improving reply speed and follow-up.',
  'Google can bring inquiries, but clinics still need to answer quickly to win appointments. Clinifly helps your team and AI assistant keep those conversations active from first message to booking. The goal is better conversion from demand you already have.',
  'en',
  54,
  45,
  ARRAY['objection', 'google_inquiries', 'reply_speed', 'booking_rate']
),
(
  'playbook.en.046',
  'objection_handling',
  'patient_count_expectation',
  'How many patients will Clinifly bring me?',
  ARRAY['Can you guarantee a specific number of new patients?', 'How many inquiries per month will we receive?', 'What exact patient volume can Clinifly promise?'],
  'We do not guarantee patient numbers; results depend on your clinic, market, and follow-up quality.',
  'It is not honest to promise exact patient numbers. Clinifly helps improve important drivers such as faster replies, better communication, and stronger inquiry-to-appointment conversion. Final results vary by each clinic''s offer, pricing, team, and market conditions.',
  'en',
  88,
  46,
  ARRAY['objection', 'no_guarantees', 'realistic_expectations', 'patient_count']
),
(
  'playbook.en.047',
  'objection_handling',
  'revenue_guarantee_concern',
  'Do you guarantee revenue growth?',
  ARRAY['Will Clinifly guarantee income increase for our clinic?', 'Can you promise a return on investment?', 'Is revenue growth guaranteed with Clinifly?'],
  'No. We do not guarantee revenue, but we help improve communication that supports better booking outcomes.',
  'Revenue depends on many factors beyond software, such as treatment pricing, close rates, and market demand. Clinifly focuses on what we can improve responsibly: more inquiries, faster responses, and better conversion to appointments. This supports growth potential without unrealistic promises.',
  'en',
  87,
  47,
  ARRAY['objection', 'revenue_question', 'no_revenue_promise', 'better_bookings']
),
(
  'playbook.en.048',
  'objection_handling',
  'platform_fatigue',
  'Why should I join another platform if my clinic is already busy?',
  ARRAY['We are overloaded already, why add Clinifly now?', 'Will another tool create extra work?', 'Is Clinifly worth it when team capacity is limited?'],
  'Clinifly is made to reduce repetitive message work, not add more work for your staff.',
  'Busy clinics often need faster first replies the most. Clinifly AI can answer common questions and keep chats active while your team handles key cases. This reduces daily pressure and helps your staff focus on appointment-ready patients.',
  'en',
  51,
  48,
  ARRAY['objection', 'busy_team', 'less_repetitive_work', 'ai_help']
),
(
  'playbook.en.049',
  'objection_handling',
  'skepticism_about_new_tools',
  'How is Clinifly not just another marketing tool?',
  ARRAY['Is Clinifly more than simple advertising software?', 'What makes Clinifly useful for clinics day to day?', 'Why is Clinifly different from generic marketing tools?'],
  'Clinifly is not only for visibility; it helps your clinic turn inquiries into appointments with faster communication.',
  'Many tools help clinics get attention, but they stop there. Clinifly also helps with what happens next: answering patient questions, requesting photos, sharing treatment information, and continuing chats 24/7. That is why it supports real appointment conversion, not just impressions.',
  'en',
  50,
  49,
  ARRAY['objection', 'beyond_marketing', 'inquiry_to_appointment', 'real_use']
),
(
  'playbook.en.050',
  'objection_handling',
  'final_join_decision',
  'What is the safest way to decide if Clinifly is right for us?',
  ARRAY['How can we evaluate Clinifly with low risk?', 'What is the best way to test Clinifly before paying?', 'How should a clinic make a smart join decision?'],
  'Register free, use the 2-month no-card trial, and decide based on your real inquiry and appointment results.',
  'The safest approach is to test Clinifly in your daily clinic routine. Track response speed, staff time saved, and how many inquiries move toward appointment booking. With free registration and a two-month trial, you can decide with real data and low risk.',
  'en',
  49,
  50,
  ARRAY['decision', 'free_trial', 'low_risk', 'measure_results']
)
ON CONFLICT (id) DO UPDATE SET
  section = EXCLUDED.section,
  intent = EXCLUDED.intent,
  question = EXCLUDED.question,
  question_aliases = EXCLUDED.question_aliases,
  short_answer = EXCLUDED.short_answer,
  detailed_answer = EXCLUDED.detailed_answer,
  language = EXCLUDED.language,
  priority = EXCLUDED.priority,
  sort_order = EXCLUDED.sort_order,
  tags = EXCLUDED.tags,
  is_active = true,
  version = clinifly_partner_clinic_playbook_entries.version + 1,
  updated_at = now();
